### ISSUE TITLE
Show page renders raw (truncated) html 

### ISSUE THREAD

**Issue by GeekOnCoffee** [headwayio/administrate-field-trix#1]
Thinking at the very least we leverage some configuration of http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize prior to truncation, and possibly add a `length` option to the field which determines how much content gets shown. 

Thoughts @noahsettersten @jondkinney

**Comment by noahsettersten** [comment]
I think both of those are great options, with the exception that we may want to see the HTML rendered on the show page as a preview for the edited text. The index/collection view would be ideal to strip all of that out though.

**Comment by GeekOnCoffee** [comment]
I think I figured out a sanitize config that allowed all the HTML that trix will input, but filtered out anything explicit.
